services:
  app:
    build: .
    container_name: app-remix-notes
    command: npm run start
    ports:
      - 3000:3000
    volumes:
      - sqlite-remix-notes:/myapp/prisma
volumes:
  sqlite-remix-notes:
    driver: local
